create table public.clients (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  last_name character varying not null,
  phone_number character varying null,
  locality character varying null,
  email character varying null,
  cover text null,
  contact_method text null,
  referred_to text null,
  constraint clients_pkey primary key (id)
) TABLESPACE pg_default;

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select clients"
ON public.clients
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert clients"
ON public.clients
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public delete clients"
ON public.clients
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Public update clients"
ON public.clients
FOR UPDATE
TO authenticated
USING (true);
