create table public.stock_supplies (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  supply_line character varying null,
  supply_code character varying not null,
  supply_description character varying null,
  supply_color character varying not null,
  supply_quantity_for_lump bigint not null,
  supply_quantity_lump bigint not null,
  supply_quantity bigint not null,
  supply_site character varying not null,
  supply_material character varying not null,
  supply_price numeric(10, 2) null,
  supply_category character varying not null,
  last_update timestamp without time zone null,
  supply_brand character varying null,
  image_id bigint null,
  constraint stock_supplies_pkey primary key (id),
  constraint chk_supply_price_non_negative check ((supply_price >= (0)::numeric)),
  constraint chk_supply_quantity_for_lump_non_negative check ((supply_quantity_for_lump >= 0)),
  constraint chk_supply_quantity_lump_non_negative check ((supply_quantity_lump >= 0)),
  constraint chk_supply_quantity_non_negative check ((supply_quantity >= 0))
) TABLESPACE pg_default;

create table public.gallery_supplies (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  supply_code character varying not null,
  image_url character varying null,
  image_path character varying null,
  constraint gallery_supplies_pkey primary key (id)
) TABLESPACE pg_default;

alter table public.stock_supplies
  add constraint stock_supplies_image_id_fkey
  foreign key (image_id) references public.gallery_supplies (id) on update CASCADE on delete SET NULL;


ALTER TABLE public.gallery_supplies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select gallery_supplies"
ON public.gallery_supplies
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert gallery_supplies"
ON public.gallery_supplies
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public delete gallery_supplies"
ON public.gallery_supplies
FOR DELETE
TO authenticated
USING (true);