create table public.employee_documents (
  id bigint generated by default as identity not null,
  uploaded_at timestamp with time zone not null default now(),
  employee_id bigint not null,
  path text not null,
  title text null,
  description text null,
  type text null,
  size bigint null,
  constraint employee_documents_pkey primary key (id),
  constraint employee_documents_employee_id_fkey foreign KEY (employee_id) references employees (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

------ INDEXES ------

create index if not exists employee_documents_employee_id_idx
  on public.employee_documents using btree (employee_id) TABLESPACE pg_default;

------ RLS ------
-- Employee documents are sensitive, so they stay admin only.

ALTER TABLE public.employee_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Employee documents select"
ON public.employee_documents
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Employee documents insert"
ON public.employee_documents
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Employee documents update"
ON public.employee_documents
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Employee documents delete"
ON public.employee_documents
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ BUCKET ------
-- Create a private bucket named 'employees' before running these policies.

INSERT INTO storage.buckets (id, name, public)
VALUES ('employees', 'employees', false)
ON CONFLICT (id) DO NOTHING;

------ BUCKET POLICIES ------

CREATE POLICY "employee documents select"
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'employees'
    AND EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "employee documents insert"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'employees'
    AND EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "employee documents delete"
ON storage.objects
FOR DELETE
TO authenticated
USING (
    bucket_id = 'employees'
    AND EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);
