create table public.employees (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null,
  name text not null,
  last_name text not null,
  identity_number text null,
  birth_date date null,
  phone_number text null,
  email text null,
  address text null,
  locality text null,
  position text null,
  hire_date date null,
  termination_date date null,
  status text not null default 'Activo',
  emergency_contact_name text null,
  emergency_contact_phone text null,
  notes text null,
  constraint employees_pkey primary key (id),
  constraint employees_user_id_key unique (user_id),
  constraint employees_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE on delete set null
) TABLESPACE pg_default;

------ INDEXES ------

create index if not exists employees_last_name_idx
  on public.employees using btree (last_name) TABLESPACE pg_default;

------ RLS ------
-- The whole module is admin only, both to read and to write.

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Employees select"
ON public.employees
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Employees insert"
ON public.employees
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Employees update"
ON public.employees
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Employees delete"
ON public.employees
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);
