create table public.employee_evaluations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  employee_id bigint not null,
  year bigint not null,
  -- 0 = enero ... 11 = diciembre, same convention as monthly_settlements
  month bigint not null,
  rating smallint not null,
  notes text null,
  evaluated_by uuid null,
  constraint employee_evaluations_pkey primary key (id),
  constraint employee_evaluations_employee_year_month_unique unique (employee_id, year, month),
  constraint employee_evaluations_rating_check check (
    rating >= 1
    and rating <= 5
  ),
  constraint employee_evaluations_month_check check (
    month >= 0
    and month <= 11
  ),
  constraint employee_evaluations_employee_id_fkey foreign KEY (employee_id) references employees (id) on update CASCADE on delete CASCADE,
  constraint employee_evaluations_evaluated_by_fkey foreign KEY (evaluated_by) references users (uid_user) on update CASCADE on delete set null
) TABLESPACE pg_default;

------ INDEXES ------

create index if not exists employee_evaluations_employee_id_idx
  on public.employee_evaluations using btree (employee_id) TABLESPACE pg_default;

create index if not exists employee_evaluations_period_idx
  on public.employee_evaluations using btree (year, month) TABLESPACE pg_default;

------ TRIGGERS ------

create or replace function public.set_employee_evaluations_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger employee_evaluations_set_updated_at
  before update on public.employee_evaluations
  for each row
  execute function public.set_employee_evaluations_updated_at();

------ RLS ------
-- Evaluations are admin only, same as the rest of the module.

ALTER TABLE public.employee_evaluations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Employee evaluations select"
ON public.employee_evaluations
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Employee evaluations insert"
ON public.employee_evaluations
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Employee evaluations update"
ON public.employee_evaluations
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Employee evaluations delete"
ON public.employee_evaluations
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);
