create table public.vacation_requests (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid not null,
  start_date date not null,
  end_date date not null,
  reason text null,
  status text not null default 'Pendiente',
  reviewer_notes text null,
  reviewed_by uuid null,
  reviewed_at timestamp with time zone null,
  constraint vacation_requests_pkey primary key (id),
  constraint vacation_requests_dates_check check (end_date >= start_date),
  constraint vacation_requests_status_check check (
    status in ('Pendiente', 'Aprobada', 'Rechazada')
  ),
  constraint vacation_requests_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE on delete CASCADE,
  constraint vacation_requests_reviewed_by_fkey foreign KEY (reviewed_by) references users (uid_user) on update CASCADE on delete set null
) TABLESPACE pg_default;

------ INDEXES ------

create index if not exists vacation_requests_user_id_idx
  on public.vacation_requests using btree (user_id) TABLESPACE pg_default;

create index if not exists vacation_requests_status_idx
  on public.vacation_requests using btree (status) TABLESPACE pg_default;

------ TRIGGERS ------

create or replace function public.set_vacation_requests_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger vacation_requests_set_updated_at
  before update on public.vacation_requests
  for each row
  execute function public.set_vacation_requests_updated_at();

------ RLS ------
-- Unlike the rest of the module, every authenticated user takes part here:
-- they read and create their own requests, and only admins resolve them.

ALTER TABLE public.vacation_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Vacation requests select"
ON public.vacation_requests
FOR SELECT
TO authenticated
USING (
    user_id = auth.uid()
    OR EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

-- A request is always created for yourself and always starts as pending.
CREATE POLICY "Vacation requests insert"
ON public.vacation_requests
FOR INSERT
TO authenticated
WITH CHECK (
    user_id = auth.uid()
    AND status = 'Pendiente'
);

-- Only admins approve or reject.
CREATE POLICY "Vacation requests update"
ON public.vacation_requests
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

-- You can cancel your own request while nobody resolved it yet.
CREATE POLICY "Vacation requests delete"
ON public.vacation_requests
FOR DELETE
TO authenticated
USING (
    (user_id = auth.uid() AND status = 'Pendiente')
    OR EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);
