create table public.modules_files (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  storage_path text not null,
  module_id bigint not null,
  file_name text null,
  description text null,
  constraint modules_files_pkey primary key (id),
  constraint modules_files_module_id_fkey foreign KEY (module_id) references modules (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

------ Indexes -----

CREATE INDEX idx_modules_files_module_id
ON public.modules_files (module_id);

CREATE UNIQUE INDEX idx_modules_files_storage_path
ON public.modules_files (storage_path);

------ Policies -----

CREATE POLICY "Modules_files select"
ON public.modules_files
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR EXISTS (
        SELECT 1
        FROM public.modules m
        WHERE m.id = modules_files.module_id
          AND m.user_id = auth.uid()
    )
);

CREATE POLICY "Modules_files insert"
ON public.modules_files
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR EXISTS (
        SELECT 1
        FROM public.modules m
        WHERE m.id = modules_files.module_id
          AND m.user_id = auth.uid()
    )
);

CREATE POLICY "Modules_files update"
ON public.modules_files FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR EXISTS (
        SELECT 1
        FROM public.modules m
        WHERE m.id = modules_files.module_id
          AND m.user_id = auth.uid()
    )
);

CREATE POLICY "Modules_files delete"
ON public.modules_files FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR EXISTS (
        SELECT 1
        FROM public.modules m
        WHERE m.id = modules_files.module_id
          AND m.user_id = auth.uid()
    )
);
