create table public.modules_monthly_settlements (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  year bigint not null,
  month bigint not null,
  user_id uuid not null,
  amount numeric not null,
  modules_count integer not null default 0,
  constraint modules_monthly_settlements_pkey primary key (id),
  constraint modules_monthly_settlements_user_year_month_unique unique (user_id, year, month),
  constraint modules_monthly_settlements_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

------ INDEXES ------

CREATE INDEX idx_modules_monthly_settlements_user_id
ON public.modules_monthly_settlements (user_id);

------ RLS ------

ALTER TABLE public.modules_monthly_settlements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Modules monthly settlements select"
ON public.modules_monthly_settlements
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR user_id = auth.uid()
);

CREATE POLICY "Modules monthly settlements insert"
ON public.modules_monthly_settlements
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Modules monthly settlements update"
ON public.modules_monthly_settlements
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Modules monthly settlements delete"
ON public.modules_monthly_settlements
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);
