create table public.modules_files (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  storage_path text not null,
  module_id bigint not null,
  file_name text null,
  description text null,
  admin_description text null,
  status text null,
  constraint modules_files_pkey primary key (id),
  constraint modules_files_module_id_fkey foreign KEY (module_id) references modules (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

------ Indexes -----

CREATE INDEX idx_modules_files_module_id
ON public.modules_files (module_id);

CREATE UNIQUE INDEX idx_modules_files_storage_path
ON public.modules_files (storage_path);

------ Policies -----

CREATE POLICY "Modules_files select"
ON public.modules_files
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR EXISTS (
        SELECT 1
        FROM public.modules m
        WHERE m.id = modules_files.module_id
          AND m.user_id = auth.uid()
    )
);

CREATE POLICY "Modules_files insert"
ON public.modules_files
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR EXISTS (
        SELECT 1
        FROM public.modules m
        WHERE m.id = modules_files.module_id
          AND m.user_id = auth.uid()
    )
);

CREATE POLICY "Modules_files update"
ON public.modules_files FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR EXISTS (
        SELECT 1
        FROM public.modules m
        WHERE m.id = modules_files.module_id
          AND m.user_id = auth.uid()
    )
);

CREATE POLICY "Modules_files delete"
ON public.modules_files FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR EXISTS (
        SELECT 1
        FROM public.modules m
        WHERE m.id = modules_files.module_id
          AND m.user_id = auth.uid()
    )
);

------ Triggers -----

CREATE OR REPLACE FUNCTION public.modules_files_guard_review_columns()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean;
  v_is_owner boolean;
BEGIN
  IF auth.role() = 'service_role' THEN
    RETURN NEW;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.users
    WHERE uid_user = auth.uid()
      AND role = 'Admin'
  ) INTO v_is_admin;

  IF v_is_admin THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW.status IS NOT NULL
       OR NEW.admin_description IS NOT NULL
    THEN
      RAISE EXCEPTION 'Solo un Admin puede aprobar, rechazar o modificar la devolución del archivo';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW.admin_description IS DISTINCT FROM OLD.admin_description THEN
    RAISE EXCEPTION 'Solo un Admin puede modificar la devolución del archivo';
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NEW.status IS NOT NULL THEN
      RAISE EXCEPTION 'Solo un Admin puede aprobar o rechazar el archivo';
    END IF;

    IF OLD.status IS DISTINCT FROM 'rejected' THEN
      RAISE EXCEPTION 'Solo se pueden reenviar a revisión archivos rechazados';
    END IF;

    SELECT EXISTS (
      SELECT 1 FROM public.modules m
      WHERE m.id = NEW.module_id
        AND m.user_id = auth.uid()
    ) INTO v_is_owner;

    IF NOT v_is_owner THEN
      RAISE EXCEPTION 'Solo el dueño del módulo puede reenviar el archivo a revisión';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_modules_files_guard_review_columns
BEFORE INSERT OR UPDATE ON public.modules_files
FOR EACH ROW
EXECUTE FUNCTION public.modules_files_guard_review_columns();
