create table public.modules (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null,
  status text null,
  title text null,
  description text null,
  amount numeric null,
  work_id bigint null,
  admin_description text null,
  constraint modules_pkey primary key (id),
  constraint modules_work_id_fkey foreign KEY (work_id) references works (id) on update CASCADE,
  constraint modules_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE on delete set null
) TABLESPACE pg_default;

------ Indexes -----

CREATE INDEX idx_modules_user_id
ON public.modules (user_id);

CREATE INDEX idx_modules_status
ON public.modules (status);

------ Policies -----

CREATE POLICY "Modules select"
ON public.modules FOR SELECT
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin') 
    OR ((user_id = auth.uid()))
);

CREATE POLICY "Modules insert"
ON public.modules FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
    OR (user_id = auth.uid())
);

CREATE POLICY "Modules update"
ON public.modules FOR UPDATE
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin') 
    OR ((user_id = auth.uid()))
);

CREATE POLICY "Modules delete"
ON public.modules FOR DELETE
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
    OR ((user_id = auth.uid()))
);

------ Triggers -----

CREATE OR REPLACE FUNCTION public.modules_guard_review_columns()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean;
BEGIN
  IF auth.role() = 'service_role' THEN
    RETURN NEW;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.users
    WHERE uid_user = auth.uid()
      AND role = 'Admin'
  ) INTO v_is_admin;

  IF v_is_admin THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW.admin_description IS NOT NULL
       OR NEW.status IN ('approved', 'rejected')
    THEN
      RAISE EXCEPTION 'Solo un Admin puede aprobar, rechazar o modificar la devolución del módulo';
    END IF;
  ELSE
    IF NEW.admin_description IS DISTINCT FROM OLD.admin_description
       OR (
         NEW.status IS DISTINCT FROM OLD.status
         AND NEW.status IN ('approved', 'rejected')
       )
    THEN
      RAISE EXCEPTION 'Solo un Admin puede aprobar, rechazar o modificar la devolución del módulo';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_modules_guard_review_columns
BEFORE INSERT OR UPDATE ON public.modules
FOR EACH ROW
EXECUTE FUNCTION public.modules_guard_review_columns();
