create table public.modules (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null,
  status text null,
  title text null,
  description text null,
  amount numeric null,
  work_id bigint null,
  constraint modules_pkey primary key (id),
  constraint modules_work_id_fkey foreign KEY (work_id) references works (id) on update CASCADE
  constraint modules_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE on delete set null
) TABLESPACE pg_default;

------ Indexes -----

CREATE INDEX idx_modules_user_id
ON public.modules (user_id);

CREATE INDEX idx_modules_status
ON public.modules (status);

------ Policies -----

CREATE POLICY "Modules select"
ON public.modules FOR SELECT
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin') 
    OR ((user_id = auth.uid()))
);

CREATE POLICY "Modules insert"
ON public.modules FOR INSERT
TO authenticated
WITH CHECK (
    true
);

CREATE POLICY "Modules update"
ON public.modules FOR UPDATE
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin') 
    OR ((user_id = auth.uid()))
);

CREATE POLICY "Modules delete"
ON public.modules FOR DELETE
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin') 
    OR ((user_id = auth.uid()))
);
