create table public.modules_settings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  price_per_module numeric null,
  constraint modules_settings_pkey primary key (id)
) TABLESPACE pg_default;

ALTER TABLE public.modules_settings ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.modules_settings
  ADD CONSTRAINT modules_settings_price_nonneg
  CHECK (price_per_module IS NULL OR price_per_module >= 0);

------ Policies -----

CREATE POLICY "Modules settings select"
ON public.modules_settings
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Modules settings insert"
ON public.modules_settings
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Modules settings update"
ON public.modules_settings
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Modules settings delete"
ON public.modules_settings
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);
