create table public.transactions_income (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    date date null,
    cash_box_id bigint null,
    amount_ars numeric null,
    quote_usd numeric null,
    amount_usd numeric null,
    category_income_id bigint null,
    bank_account_id bigint null,
    payment_method_id bigint null,
    description character varying null,
    constraint transactions_pkey primary key (id),
    constraint transactions_cash_box_id_fkey foreign key (cash_box_id) references public.cash_boxes (id) on update CASCADE on delete CASCADE,
    constraint transactions_bank_account_id_fkey foreign key (bank_account_id) references public.bank_accounts (id) on update CASCADE on delete SET NULL,
    constraint transactions_payment_method_id_fkey foreign key (payment_method_id) references public.payment_methods (id) on update CASCADE on delete SET NULL,
    constraint transactions_category_income_id_fkey foreign key (category_income_id) references public.category_income (id) on update CASCADE on delete SET NULL,
    constraint chk_amount_non_negative check ((amount_ars >= (0)::numeric))
) TABLESPACE pg_default;

create table public.transactions_expense (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    date date null,
    cash_box_id bigint null,
    amount_ars numeric null,
    quote_usd numeric null,
    amount_usd numeric null,
    category_expense_id bigint null,
    bank_account_id bigint null,
    payment_method_id bigint null,
    description character varying null,
    constraint transactions_pkey primary key (id),
    constraint transactions_cash_box_id_fkey foreign key (cash_box_id) references public.cash_boxes (id) on update CASCADE on delete CASCADE,
    constraint transactions_bank_account_id_fkey foreign key (bank_account_id) references public.bank_accounts (id) on update CASCADE on delete SET NULL,
    constraint transactions_payment_method_id_fkey foreign key (payment_method_id) references public.payment_methods (id) on update CASCADE on delete SET NULL,
    constraint transactions_category_expense_id_fkey foreign key (category_expense_id) references public.category_expense (id) on update CASCADE on delete SET NULL,
    constraint chk_amount_non_negative check ((amount_ars >= (0)::numeric))
) TABLESPACE pg_default;

