create table public.events (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  description character varying null,
  title character varying null,
  client_id bigint null,
  client_name character varying null,
  location character varying null,
  date date null,
  address character varying null,
  status character varying null,
  is_overdue boolean null default false,
  remember boolean null default false,
  type_id bigint null,
  constraint events_pkey primary key (id)
  constraint events_type_id_fkey foreign KEY (type_id) references events_types (id) on update CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select events"
ON public.events
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert events"
ON public.events
FOR INSERT
TO authenticated  
WITH CHECK (true);

CREATE POLICY "Public delete events"
ON public.events
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Public update events"
ON public.events
FOR UPDATE
TO authenticated
USING (true);

create table public.events_types (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  color text not null,
  name text not null,
  constraint events_types_pkey primary key (id),
  constraint events_types_color_key unique (color),
  constraint events_types_name_key unique (name)
) TABLESPACE pg_default;

ALTER TABLE public.events_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select events_types"
ON public.events_types
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert events_types"
ON public.events_types
FOR INSERT
TO authenticated  
WITH CHECK (true);

CREATE POLICY "Public delete events_types"
ON public.events_types
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Public update events_types"
ON public.events_types
FOR UPDATE
TO authenticated
USING (true);