create table public.events (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  description character varying null,
  title character varying null,
  client_name character varying null,
  date date null,
  status character varying null,
  is_overdue boolean null default false,
  remember boolean null default false,
  type_id bigint null,
  client_id bigint null,
  work_id bigint null,
  work_location text null,
  constraint events_pkey primary key (id),
  constraint events_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete set null,
  constraint events_type_id_fkey foreign KEY (type_id) references events_types (id) on update CASCADE on delete set null,
  constraint events_work_id_fkey foreign KEY (work_id) references works (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select events"
ON public.events
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert events"
ON public.events
FOR INSERT
TO authenticated  
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public delete events"
ON public.events
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.users u
    WHERE u.uid_user = auth.uid()
      AND u.role = 'Admin'
  )
);

CREATE POLICY "Public update events"
ON public.events
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.users u
    WHERE u.uid_user = auth.uid()
      AND u.role = 'Admin'
  )
)
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

create table public.events_types (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  color text not null,
  name text not null,
  constraint events_types_pkey primary key (id),
  constraint events_types_color_key unique (color),
  constraint events_types_name_key unique (name)
) TABLESPACE pg_default;

ALTER TABLE public.events_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select events_types"
ON public.events_types
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert events_types"
ON public.events_types
FOR INSERT
TO authenticated  
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public delete events_types"
ON public.events_types
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update events_types"
ON public.events_types
FOR UPDATE
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
)
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);
