create table public.budget_signatures (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  budget_id bigint not null,
  -- Secret handed to the client: the only thing needed to open the signing page.
  public_token uuid not null default gen_random_uuid (),
  -- Document sent to sign, in the 'clients' bucket. Usually budgets.pdf_path.
  document_path text not null,
  -- Where the signature goes. Coordinates are fractions of the page (0 to 1)
  -- with the origin at the top left, so they hold at any render scale.
  page_number bigint not null default 1,
  position_x numeric not null,
  position_y numeric not null,
  width numeric not null,
  height numeric not null,
  status text not null default 'Pendiente',
  -- Filled in once the client signs.
  signer_name text null,
  signed_document_path text null,
  signed_at timestamp with time zone null,
  expires_at timestamp with time zone null,
  created_by uuid null,
  constraint budget_signatures_pkey primary key (id),
  constraint budget_signatures_public_token_key unique (public_token),
  constraint budget_signatures_status_check check (
    status in ('Pendiente', 'Firmado', 'Cancelado')
  ),
  constraint budget_signatures_page_check check (page_number >= 1),
  constraint budget_signatures_position_check check (
    position_x >= 0 and position_x <= 1
    and position_y >= 0 and position_y <= 1
    and width > 0 and width <= 1
    and height > 0 and height <= 1
  ),
  constraint budget_signatures_budget_id_fkey foreign KEY (budget_id) references budgets (id) on update CASCADE on delete CASCADE,
  constraint budget_signatures_created_by_fkey foreign KEY (created_by) references users (uid_user) on update CASCADE on delete set null
) TABLESPACE pg_default;

------ INDEXES ------

create index if not exists budget_signatures_budget_id_idx
  on public.budget_signatures using btree (budget_id) TABLESPACE pg_default;

-- Only one live link per budget, so an old link cannot be signed by mistake.
create unique index if not exists budget_signatures_active_budget_idx
  on public.budget_signatures using btree (budget_id)
  where (status = 'Pendiente');

------ TRIGGERS ------

create or replace function public.set_budget_signatures_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger budget_signatures_set_updated_at
  before update on public.budget_signatures
  for each row
  execute function public.set_budget_signatures_updated_at();

------ RLS ------
-- The signing page never touches Supabase directly: it goes through API routes
-- that use the service role and hand back only that one signature request.
-- So there is no policy for the anon role here, on purpose.

ALTER TABLE public.budget_signatures ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Budget signatures select"
ON public.budget_signatures
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Budget signatures insert"
ON public.budget_signatures
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Budget signatures update"
ON public.budget_signatures
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Budget signatures delete"
ON public.budget_signatures
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);
