------- Cash flow categories table ------

create table public.cash_flow_categories (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  kind text not null,
  is_active boolean not null default true,
  constraint cash_flow_categories_pkey primary key (id),
  constraint cash_flow_categories_name_length_check check (char_length(trim(name)) > 0 and char_length(name) <= 60),
  constraint cash_flow_categories_name_trimmed_check check (name = trim(name)),
  constraint cash_flow_categories_kind_check check (kind in ('income', 'expense', 'fixed_expense', 'payment', 'collection'))
) TABLESPACE pg_default;

------ INDEXES ------

create unique index cash_flow_categories_kind_name_unique_idx on public.cash_flow_categories (kind, lower(trim(name)));

------ RLS ------

ALTER TABLE public.cash_flow_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select cash_flow_categories"
ON public.cash_flow_categories
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public insert cash_flow_categories"
ON public.cash_flow_categories
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete cash_flow_categories"
ON public.cash_flow_categories
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update cash_flow_categories"
ON public.cash_flow_categories
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);
