-- Method to get the unread messages count for a user across all channels

CREATE OR REPLACE FUNCTION public.get_unread_messages_count(p_user_id uuid)
 RETURNS bigint
 LANGUAGE sql
AS $function$
    select coalesce(sum(unread_count), 0)
    from get_unread_counts_by_channel(p_user_id);
$function$

-- Method to get the unread messages count for a user by channel

CREATE OR REPLACE FUNCTION public.get_unread_counts_by_channel(p_user_id uuid)
 RETURNS TABLE(channel_id bigint, unread_count bigint)
 LANGUAGE sql
AS $function$
    select
        cm.channel_id,
        count(m.id) as unread_count
    from channel_members cm
    left join messages m
      on m.channel_id = cm.channel_id
     and m.id > coalesce(cm.last_read_message_id, 0)
     and m.user_id <> p_user_id
     -- and m.deleted_at is null. -- Uncomment this line if we want to mark deleted messages as unread
    where cm.user_id = p_user_id
    group by cm.channel_id;
$function$

-- Method to update the last_message_id in the channels table when a new message is inserted

create or replace function set_last_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update channels
  set last_message_id = NEW.id
  where id = NEW.channel_id;

  return NEW;
end;
$$;

------ Method to update the last_read_message_id in the channel_members table when a new message is inserted

CREATE OR REPLACE FUNCTION set_last_read_message()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE channel_members
  SET last_read_message_id = NEW.id
  WHERE channel_id = NEW.channel_id
    AND user_id = NEW.user_id;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_set_last_read_message
AFTER INSERT ON messages
FOR EACH ROW
EXECUTE FUNCTION set_last_read_message();

------ Channel members ------

create table public.channel_members (
  id bigint generated by default as identity not null,
  joined_at timestamp with time zone not null default now(),
  channel_id bigint null,
  last_read_message_id bigint null,
  user_id uuid null,
  constraint channel_members_pkey primary key (id),
  constraint channel_members_channel_id_fkey foreign KEY (channel_id) references channels (id) on update CASCADE on delete CASCADE,
  constraint channel_members_last_read_message_id_fkey foreign KEY (last_read_message_id) references messages (id) on delete set null,
  constraint channel_members_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE POLICY "Channel members select"
ON public.channel_members FOR SELECT
TO authenticated
USING (
    user_id = auth.uid()
    OR
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
);

CREATE POLICY "Channel members insert"
ON public.channel_members FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
);

CREATE POLICY "Channel members update"
ON public.channel_members FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Channel members delete"
ON public.channel_members FOR DELETE
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
);

CREATE OR REPLACE FUNCTION public.is_channel_member(channel_id bigint, user_id uuid)
RETURNS boolean
SECURITY DEFINER
LANGUAGE sql
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.channel_members
    WHERE channel_members.channel_id = $1
    AND channel_members.user_id = $2
  );
$$;

DROP POLICY IF EXISTS "Channel members select" ON public.channel_members;
CREATE POLICY "Channel members select"
ON public.channel_members FOR SELECT
TO authenticated
USING (
  user_id = auth.uid()
  OR
  public.is_channel_member(channel_id, auth.uid())
  OR
  EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
);

------ Channels ------

create table public.channels (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  description text null,
  last_message_id bigint null,
  constraint channels_pkey primary key (id)
) TABLESPACE pg_default;

CREATE POLICY "Channels select"
ON public.channels FOR SELECT
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.channel_members cm WHERE cm.channel_id = id AND cm.user_id = auth.uid())
    OR
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
);

CREATE POLICY "Channels insert"
ON public.channels FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
);

CREATE POLICY "Channels update"
ON public.channels FOR UPDATE
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
);

CREATE POLICY "Channels delete"
ON public.channels FOR DELETE
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
);

------ Messages ------

create table public.messages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  channel_id bigint null,
  edited_at timestamp with time zone null,
  deleted_at timestamp with time zone null,
  reply_to bigint null,
  user_id uuid null,
  constraint messages_pkey primary key (id),
  constraint messages_channel_id_fkey foreign KEY (channel_id) references channels (id) on update CASCADE on delete CASCADE,
  constraint messages_reply_to_fkey foreign KEY (reply_to) references messages (id) on delete set null,
  constraint messages_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_messages_channel_created on public.messages using btree (channel_id, created_at desc) TABLESPACE pg_default;

create trigger trg_set_last_message
after INSERT on messages for EACH row
execute FUNCTION set_last_message ();

CREATE POLICY "Messages select"
ON public.messages FOR SELECT
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.channel_members cm WHERE cm.channel_id = channel_id AND cm.user_id = auth.uid())
    OR
    EXISTS (SELECT 1 FROM public.users u WHERE u.uid_user = auth.uid() AND u.role = 'Admin')
);

CREATE POLICY "Messages insert"
ON public.messages FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (SELECT 1 FROM public.channel_members cm WHERE cm.channel_id = channel_id AND cm.user_id = auth.uid())
);

CREATE POLICY "Messages update"
ON public.messages FOR UPDATE
TO authenticated
USING (
    user_id = auth.uid()
);

CREATE POLICY "Messages delete"
ON public.messages FOR DELETE
TO authenticated
USING (
    user_id = auth.uid()
);

------ Push Notifications ------

create table public.push_subscriptions (
  id bigserial not null,
  user_id uuid not null default gen_random_uuid (),
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint push_subscriptions_pkey primary key (id),
  constraint push_subscriptions_endpoint_key unique (endpoint),
  constraint push_subscriptions_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_push_subscriptions_user_id on public.push_subscriptions using btree (user_id) TABLESPACE pg_default;

create trigger push_subscriptions_updated_at BEFORE
update on push_subscriptions for EACH row
execute FUNCTION update_push_subscriptions_updated_at ();

CREATE POLICY "Public select push_subscriptions"
ON public.push_subscriptions
FOR SELECT
TO authenticated
USING true;

CREATE POLICY "Public insert push_subscriptions"
ON public.push_subscriptions
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Public delete push_subscriptions"
ON public.push_subscriptions
FOR DELETE
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Public update push_subscriptions"
ON public.push_subscriptions
FOR UPDATE
TO authenticated
USING (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.update_push_subscriptions_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
	NEW.updated_at = NOW();
	RETURN NEW;
END;
$function$
