------ SETTINGS ------
-- Single row (id = 1) with the public booking configuration.

create table public.appointment_settings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  -- One entry per weekday, indexed 0 = domingo ... 6 = sábado:
  -- [{ "enabled": true, "start": "09:00", "end": "18:00" }, ...]
  weekly_schedule jsonb not null default '[]'::jsonb,
  slot_duration_minutes bigint not null default 60,
  -- How far in advance a client must book, and how far ahead the calendar goes.
  min_notice_hours bigint not null default 24,
  max_days_ahead bigint not null default 30,
  -- Turns the public page on and off without deleting anything.
  is_public_enabled boolean not null default true,
  -- Event type used when an accepted appointment becomes a calendar event.
  event_type_id bigint null,
  constraint appointment_settings_pkey primary key (id),
  constraint appointment_settings_event_type_id_fkey foreign KEY (event_type_id) references events_types (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

insert into public.appointment_settings (id, weekly_schedule)
values (
  1,
  '[
    {"enabled": false, "start": "09:00", "end": "18:00"},
    {"enabled": true,  "start": "09:00", "end": "18:00"},
    {"enabled": true,  "start": "09:00", "end": "18:00"},
    {"enabled": true,  "start": "09:00", "end": "18:00"},
    {"enabled": true,  "start": "09:00", "end": "18:00"},
    {"enabled": true,  "start": "09:00", "end": "18:00"},
    {"enabled": false, "start": "09:00", "end": "13:00"}
  ]'::jsonb
)
on conflict (id) do nothing;

------ BLOCKED DATES ------
-- Holidays or any single day the business does not take appointments.

create table public.appointment_blocked_dates (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  date date not null,
  reason text null,
  constraint appointment_blocked_dates_pkey primary key (id),
  constraint appointment_blocked_dates_date_key unique (date)
) TABLESPACE pg_default;

------ APPOINTMENTS ------

create table public.appointments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  -- Secret handed to the client so they can check the status of their request.
  public_token uuid not null default gen_random_uuid (),
  client_name text not null,
  client_email text not null,
  client_phone text null,
  date date not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  -- What the client wrote: presencial, en tal lugar, etc.
  notes text null,
  status text not null default 'Pendiente',
  admin_notes text null,
  reviewed_by uuid null,
  reviewed_at timestamp with time zone null,
  -- Calendar event created when the appointment is accepted.
  event_id bigint null,
  constraint appointments_pkey primary key (id),
  constraint appointments_public_token_key unique (public_token),
  constraint appointments_time_check check (end_time > start_time),
  constraint appointments_status_check check (
    status in ('Pendiente', 'Aceptada', 'Rechazada', 'Cancelada')
  ),
  constraint appointments_reviewed_by_fkey foreign KEY (reviewed_by) references users (uid_user) on update CASCADE on delete set null,
  constraint appointments_event_id_fkey foreign KEY (event_id) references events (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

------ INDEXES ------

create index if not exists appointments_date_idx
  on public.appointments using btree (date) TABLESPACE pg_default;

create index if not exists appointments_status_idx
  on public.appointments using btree (status) TABLESPACE pg_default;

-- Stops two clients from taking the same slot: only one live appointment per slot.
create unique index if not exists appointments_active_slot_idx
  on public.appointments using btree (date, start_time)
  where (status in ('Pendiente', 'Aceptada'));

------ TRIGGERS ------

create or replace function public.set_appointments_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger appointments_set_updated_at
  before update on public.appointments
  for each row
  execute function public.set_appointments_updated_at();

create trigger appointment_settings_set_updated_at
  before update on public.appointment_settings
  for each row
  execute function public.set_appointments_updated_at();

------ RLS ------
-- The public booking page never touches these tables directly: it goes through
-- API routes that use the service role and return only free/busy slots.
-- So there is no policy for the anon role anywhere here, on purpose.

ALTER TABLE public.appointment_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointment_blocked_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Appointment settings select"
ON public.appointment_settings
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
);

CREATE POLICY "Appointment settings update"
ON public.appointment_settings
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
);

CREATE POLICY "Appointment blocked dates select"
ON public.appointment_blocked_dates
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
);

CREATE POLICY "Appointment blocked dates insert"
ON public.appointment_blocked_dates
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
);

CREATE POLICY "Appointment blocked dates delete"
ON public.appointment_blocked_dates
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
);

CREATE POLICY "Appointments select"
ON public.appointments
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
);

CREATE POLICY "Appointments update"
ON public.appointments
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
);

CREATE POLICY "Appointments delete"
ON public.appointments
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.uid_user = auth.uid() AND u.role = 'Admin'
    )
);
