create table public.bank_accounts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  bank character varying not null,
  account_number character varying not null,
  account_type character varying not null,
  is_active boolean not null default true,
  constraint bank_accounts_pkey primary key (id)
) TABLESPACE pg_default;

ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select bank_accounts"
ON public.bank_accounts
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert bank_accounts"
ON public.bank_accounts
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public update bank_accounts"
ON public.bank_accounts
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Public delete bank_accounts"
ON public.bank_accounts
FOR DELETE
TO authenticated
USING (true);

create table public.cash_boxes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  date date not null,
  opening_balance numeric(10, 2) not null default 0,
  closing_balance numeric(10, 2) null,
  is_closed boolean not null default false,
  closed_at timestamp with time zone null,
  notes text null,
  constraint cash_boxes_pkey primary key (id),
  constraint chk_opening_balance_non_negative check ((opening_balance >= (0)::numeric)),
  constraint chk_closing_balance_non_negative check ((closing_balance >= (0)::numeric))
) TABLESPACE pg_default;

ALTER TABLE public.cash_boxes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select cash_boxes"
ON public.cash_boxes
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert cash_boxes"
ON public.cash_boxes
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public update cash_boxes"
ON public.cash_boxes
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Public delete cash_boxes"
ON public.cash_boxes
FOR DELETE
TO authenticated
USING (true);

create table public.transactions_box (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  cash_box_id bigint not null,
  type character varying not null,
  amount numeric(10, 2) not null,
  category character varying not null,
  description character varying null,
  bank_account_id bigint null,
  reference character varying null,
  constraint transactions_pkey primary key (id),
  constraint transactions_cash_box_id_fkey foreign key (cash_box_id) references public.cash_boxes (id) on update CASCADE on delete CASCADE,
  constraint transactions_bank_account_id_fkey foreign key (bank_account_id) references public.bank_accounts (id) on update CASCADE on delete SET NULL,
  constraint chk_amount_non_negative check ((amount >= (0)::numeric))
) TABLESPACE pg_default;

ALTER TABLE public.transactions_box ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select transactions_box"
ON public.transactions_box
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert transactions_box"
ON public.transactions_box
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public update transactions_box"
ON public.transactions_box
FOR UPDATE
TO authenticated
USING (true);

CREATE POLICY "Public delete transactions_box"
ON public.transactions_box
FOR DELETE
TO authenticated
USING (true);