create table public.bank_accounts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  bank character varying not null,
  account_number character varying not null,
  account_type character varying not null,
  is_active boolean not null default true,
  constraint bank_accounts_pkey primary key (id)
) TABLESPACE pg_default;

ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select bank_accounts"
ON public.bank_accounts
FOR SELECT
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public insert bank_accounts"
ON public.bank_accounts
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public update bank_accounts"
ON public.bank_accounts
FOR UPDATE
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
)
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public delete bank_accounts"
ON public.bank_accounts
FOR DELETE
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

create table public.cash_boxes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  opening_balance numeric null default 0,
  closing_balance numeric null,
  is_closed boolean not null default false,
  closed_at timestamp with time zone null,
  notes text null,
  constraint cash_boxes_pkey primary key (id),
  constraint chk_opening_balance_non_negative check ((opening_balance >= (0)::numeric)),
  constraint chk_closing_balance_non_negative check ((closing_balance >= (0)::numeric))
) TABLESPACE pg_default;

ALTER TABLE public.cash_boxes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select cash_boxes"
ON public.cash_boxes
FOR SELECT
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public insert cash_boxes"
ON public.cash_boxes
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public update cash_boxes"
ON public.cash_boxes
FOR UPDATE
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
) 
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public delete cash_boxes"
ON public.cash_boxes
FOR DELETE
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

create table public.transactions_box (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  cash_box_id bigint not null,
  type character varying not null,
  amount numeric not null,
  category character varying not null,
  description character varying null,
  bank_account_id bigint null,
  constraint transactions_pkey primary key (id),
  constraint transactions_cash_box_id_fkey foreign key (cash_box_id) references public.cash_boxes (id) on update CASCADE on delete CASCADE,
  constraint transactions_bank_account_id_fkey foreign key (bank_account_id) references public.bank_accounts (id) on update CASCADE on delete SET NULL,
  constraint chk_amount_non_negative check ((amount >= (0)::numeric))
) TABLESPACE pg_default;

ALTER TABLE public.transactions_box ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select transactions_box"
ON public.transactions_box
FOR SELECT
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public insert transactions_box"
ON public.transactions_box
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public update transactions_box"
ON public.transactions_box
FOR UPDATE
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public delete transactions_box"
ON public.transactions_box
FOR DELETE
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

------ AUTOMATIC CLOSE CASH BOXES ------

create or replace function public.close_open_cash_box()
returns void
language plpgsql
as $$
begin
  update public.cash_boxes
  set
    is_closed = true,
    closed_at = now()
  where is_closed = false;
end;
$$;

select cron.schedule(
  'close-open-cash-box',
  '45 2 * * 1',  -- Domingo a las 23:00
  $$select public.close_open_cash_box();$$
);

------ TRIGGER TO CREATE CASH BOX TRANSACTIONS WHEN INSERTING A TRANSACTION BALANCES ------

create or replace function public.sync_balance_transaction_to_cash_box()
returns trigger
language plpgsql
as $$
declare
    v_cash_box_id bigint;
begin
    -- if the transaction is an extra amount, then we don't need to create a cash box transaction
    if coalesce(new.is_extra_amount, false) then
        return new;
    end if;

    -- Search for an open cash box
    select id
    into v_cash_box_id
    from public.cash_boxes
    where is_closed = false
    limit 1;

    -- If not exists, creste a new cash box
    if v_cash_box_id is null then
        insert into public.cash_boxes (
            created_at,
            is_closed
        )
        values (
            now(),
            false
        )
        returning id into v_cash_box_id;
    end if;

    -- Create a new cash box transaction
    insert into public.transactions_box (
        cash_box_id,
        type,
        category,
        description,
        bank_account_id,
        amount
    )
    values (
        v_cash_box_id,
        'income',
        new.payment_method,
        new.notes,
        new.bank_account_id,
        new.amount
    );

    return new;
end;
$$;

create trigger trg_sync_balance_transaction_to_cash_box
after insert on public.balance_transactions
for each row
execute function public.sync_balance_transaction_to_cash_box();