create table public.checklists (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  work_id bigint null,
  description text null,
  progress bigint null,
  name text null,
  type_furniture text null,
  width double precision null,
  height double precision null,
  notes text null,
  depth text null,
  constraint checklists_pkey primary key (id),
  constraint checklists_work_id_fkey foreign KEY (work_id) references works (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.checklists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select checklists"
ON public.checklists
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert checklists"
ON public.checklists
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public delete checklists"
ON public.checklists
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Public update checklists"
ON public.checklists
FOR UPDATE
TO authenticated
USING (true);

------ Items checklists table -------

create table public.items_checklists (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  checklist_id bigint null,
  description text null,
  done boolean null,
  sort_order numeric null,
  constraint items_checklists_pkey primary key (id),
  constraint items_checklists_checklist_id_fkey foreign KEY (checklist_id) references checklists (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

------ Materials table -------

create table public.materials (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  constraint materials_pkey primary key (id),
  constraint materials_name_key unique (name)
) TABLESPACE pg_default;

ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select materials"
ON public.materials
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert materials"
ON public.materials
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public delete materials"
ON public.materials
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Public update materials"
ON public.materials
FOR UPDATE
TO authenticated
USING (true);

------ Predefined items table -------

create table public.items_predefined (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  items jsonb null,
  material_id bigint null,
  constraint items_predefined_pkey primary key (id),
  constraint items_predefined_material_id_fkey foreign KEY (material_id) references materials (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
ALTER TABLE public.items_predefined ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select items_predefined"
ON public.items_predefined
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert items_predefined"
ON public.items_predefined
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public delete items_predefined"
ON public.items_predefined
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Public update items_predefined"
ON public.items_predefined
FOR UPDATE
TO authenticated
USING (true);

------ Gallery checklists table -------

create table public.gallery_checklists (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  path text null,
  item_id bigint null,
  title text null,
  description text null,
  constraint images_checklists_pkey primary key (id),
  constraint images_checklists_item_id_fkey foreign KEY (item_id) references items_checklists (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;