create table public.works (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  locality character varying null,
  address character varying null,
  client_id bigint null,
  status character varying null,
  architect character varying null,
  general_note character varying null,
  furniture text null,
  zone character varying null,
  hood character varying null,
  name text null,
  constraint works_pkey primary key (id),
  constraint works_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select works"
ON public.works
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert works"
ON public.works
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public delete works"
ON public.works
FOR DELETE
TO authenticated
USING (
  EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.uid_user = auth.uid()
        AND u.role = 'Admin'
  )
);

CREATE POLICY "Public update works"
ON public.works
FOR UPDATE
TO authenticated
USING (true);

------ BUCKET POLICIES ------

CREATE POLICY "works files select"
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'works-files'
);

CREATE POLICY "works files insert"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'works-files'
);

CREATE POLICY "works files delete"
ON storage.objects
FOR DELETE
TO authenticated
USING (
    bucket_id = 'works-files'
    AND EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);