create table public.works (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  locality character varying null,
  address character varying null,
  client_id bigint null,
  status character varying null,
  architect character varying null,
  general_note character varying null,
  balance_id bigint null,
  furniture text null,
  constraint works_pkey primary key (id),
  constraint works_client_id_fkey foreign KEY (client_id) references clients (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select works"
ON public.works
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Public insert works"
ON public.works
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Public delete works"
ON public.works
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Public update works"
ON public.works
FOR UPDATE
TO authenticated
USING (true);