------- Payment methods table ------

create table public.payment_methods (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  is_active boolean not null default true,
  constraint payment_methods_pkey primary key (id),
  constraint payment_methods_name_length_check check (char_length(name) <= 60)
) TABLESPACE pg_default;

------ INDEXES ------

create unique index payment_methods_name_unique_idx on public.payment_methods (lower(name));

------ RLS ------

ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select payment_methods"
ON public.payment_methods
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public insert payment_methods"
ON public.payment_methods
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete payment_methods"
ON public.payment_methods
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update payment_methods"
ON public.payment_methods
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

------- SEED DATA ------

INSERT INTO public.payment_methods (name) VALUES
  ('Efectivo'),
  ('Tarjeta de Crédito'),
  ('Tarjeta de Débito'),
  ('Transferencia Bancaria'),
  ('Cheque físico'),
  ('Echeck'),
  ('Dólar'),
  ('Otro')
ON CONFLICT (lower(name)) DO NOTHING;
