create table public.users (
  id bigint generated by default as identity not null,
  username character varying not null,
  role character varying not null,
  uid_user character varying null,
  mail text null,
  constraint users_pkey primary key (id),
  constraint users_username_key unique (username)
) TABLESPACE pg_default;