create table public.users (
  id bigint generated by default as identity not null,
  username character varying not null,
  role character varying not null,
  uid_user uuid null,
  mail text null,
  name text null,
  last_name text null,
  constraint users_pkey primary key (id),
  constraint users_username_key unique (username),
  constraint users_uid_user_fkey foreign KEY (uid_user) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE POLICY "Public update users"
ON public.users
FOR UPDATE
TO service_role
USING (true);

CREATE POLICY "Public insert users"
ON public.users
FOR INSERT
TO service_role
WITH CHECK (true);

CREATE POLICY "Public delete users"
ON public.users
FOR DELETE
TO service_role
USING (true);

CREATE POLICY "Public select users"
ON public.users
FOR SELECT
TO authenticated
USING (true);