create table public.attendance_entries (
  id bigint generated by default as identity not null,
  attendance_id bigint not null,
  type text not null,
  entry_time timestamp with time zone not null default now(),
  latitude numeric null,
  longitude numeric null,
  constraint attendance_entries_pkey primary key (id),
  constraint attendance_entries_attendance_id_fkey foreign KEY (attendance_id) references attendance (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

--- INDEXES ---

  create index if not exists idx_attendance_entries_attendance_id
  on public.attendance_entries using btree (attendance_id);

  create index if not exists idx_attendance_entries_attendance_time
  on public.attendance_entries using btree (attendance_id, entry_time desc);

--- POLICIES ---

CREATE POLICY "Attendance entries select"
ON public.attendance_entries
FOR SELECT
TO authenticated
USING (
    true
);

CREATE POLICY "Attendance entries insert"
ON public.attendance_entries
FOR INSERT
TO authenticated
WITH CHECK (
    true
);

CREATE POLICY "Attendance entries update"
ON public.attendance_entries
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Attendance entries delete"
ON public.attendance_entries
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

