create table public.attendance_entries (
    id bigint generated by default as identity not null,
    attendance_id bigint not null,
    type text not null,
    entry_time timestamp with time zone not null default now(),
    latitude numeric null,
    longitude numeric null,
    description text null,
    constraint attendance_entries_pkey primary key (id),
    constraint attendance_entries_attendance_id_fkey foreign KEY (attendance_id) references attendance (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

--- INDEXES ---

  create index if not exists idx_attendance_entries_attendance_id
  on public.attendance_entries using btree (attendance_id);

  create index if not exists idx_attendance_entries_attendance_time
  on public.attendance_entries using btree (attendance_id, entry_time desc);

--- POLICIES ---

CREATE POLICY "Attendance entries select"
ON public.attendance_entries
FOR SELECT
TO authenticated
USING (
    (EXISTS ( SELECT 1
        FROM attendance a
        WHERE ((a.id = attendance_entries.attendance_id) AND ((a.user_id = auth.uid()) OR 
            (EXISTS ( SELECT 1 FROM users u
            WHERE ((u.uid_user = auth.uid()) AND ((u.role)::text = 'Admin'::text))))))
        )
    )
);

CREATE POLICY "Attendance entries insert"
ON public.attendance_entries
FOR INSERT
TO authenticated
WITH CHECK (
    (EXISTS ( SELECT 1
        FROM attendance a
            WHERE ((a.id = attendance_entries.attendance_id) AND ((a.user_id = auth.uid()) OR 
            (EXISTS ( SELECT 1 FROM users u
            WHERE ((u.uid_user = auth.uid()) AND ((u.role)::text = 'Admin'::text))))))
        )
    )
);

CREATE POLICY "Attendance entries update"
ON public.attendance_entries
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Attendance entries delete"
ON public.attendance_entries
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

------ AUTOMATIC CLOSE OF ATTENDANCE ENTRIES ------

CREATE OR REPLACE FUNCTION public.close_pending_attendance_entries()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    argentina_date date;
    argentina_close_time timestamptz;
BEGIN
    argentina_date :=
        (CURRENT_TIMESTAMP AT TIME ZONE 'America/Argentina/Buenos_Aires')::date;

    argentina_close_time :=
        argentina_date::timestamp
        AT TIME ZONE 'America/Argentina/Buenos_Aires';

    argentina_close_time :=
        argentina_close_time + interval '23 hours';

    INSERT INTO public.attendance_entries (
        attendance_id,
        type,
        entry_time,
        description
    )
    SELECT
        latest.attendance_id,
        CASE
            WHEN latest.type = 'regular_in' THEN 'regular_out'
            WHEN latest.type = 'overtime_in' THEN 'overtime_out'
        END,
        argentina_close_time,
        'Salida automática por cierre de jornada'
    FROM (
        SELECT DISTINCT ON (ae.attendance_id)
            ae.attendance_id,
            ae.type,
            ae.entry_time,
            ae.id
        FROM public.attendance_entries ae
        INNER JOIN public.attendance a
            ON a.id = ae.attendance_id
        WHERE a.date = argentina_date
        ORDER BY ae.attendance_id, ae.entry_time DESC, ae.id DESC
    ) latest
    WHERE latest.type IN ('regular_in', 'overtime_in')
      AND NOT EXISTS (
          SELECT 1
          FROM public.attendance_entries existing
          WHERE existing.attendance_id = latest.attendance_id
            AND existing.type = CASE
                WHEN latest.type = 'regular_in' THEN 'regular_out'
                WHEN latest.type = 'overtime_in' THEN 'overtime_out'
            END
            AND existing.entry_time >= argentina_close_time
      );
END;
$$;

SELECT cron.schedule(
    'close-pending-attendance-entries',
    '0 2 * * *',
    $$SELECT public.close_pending_attendance_entries();$$
);