create table public.attendance_settings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  tolerance_quantity_minutes bigint null,
  square_meters bigint null,
  default_check_in_time text null,
  default_check_out_time text null,
  constraint attendance_settings_pkey primary key (id)
) TABLESPACE pg_default;

CREATE POLICY "Attendance settings select"
ON public.attendance_settings
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Attendance settings insert"
ON public.attendance_settings
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Attendance settings update"
ON public.attendance_settings
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Attendance settings delete"
ON public.attendance_settings
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);