create table public.attendance (
  id bigint generated by default as identity not null,
  date date not null,
  user_uid uuid not null,
  status text null,
  description text null,
  constraint attendance_pkey primary key (id),
  constraint attendance_user_uid_fkey foreign KEY (user_uid) references users (uid_user) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

--- VER INDICES

CREATE POLICY "Attendance select"
ON public.attendance
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR user_uid = auth.uid()
);

CREATE POLICY "Attendance insert"
ON public.attendance
FOR INSERT
TO authenticated
WITH CHECK (
    true
);

CREATE POLICY "Attendance update"
ON public.attendance
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Attendance delete"
ON public.attendance
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

