create table public.monthly_settlements (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  year  not null,
  month numeric not null,
  user_id uuid not null,
  amount numeric not null,
  number_hours numeric not null,
  number_overtime_hours numeric not null,
  price_hour numeric not null,
  price_overtime_hour numeric not null,
  constraint monthly_settlements_pkey primary key (id),
  constraint monthly_settlements_user_id_fkey foreign KEY (user_id) references users (uid_user) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

------ INDEXES ------

CREATE INDEX idx_monthly_settlements_user_id
ON public.monthly_settlements (user_id);

ALTER TABLE public.monthly_settlements
ADD CONSTRAINT monthly_settlements_user_year_month_unique
UNIQUE (user_id, year, month);

------ RLS ------

CREATE POLICY "Monthly settlements select"
ON public.monthly_settlements
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
    OR user_id = auth.uid()
);

CREATE POLICY "Monthly settlements insert"
ON public.monthly_settlements
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Monthly settlements update"
ON public.monthly_settlements
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

CREATE POLICY "Monthly settlements delete"
ON public.monthly_settlements
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
          AND u.role = 'Admin'
    )
);

