------- Files purchases suppliers table ------

create table public.files_purchases_suppliers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  storage_path text not null,
  purchase_supplier_id bigint not null,
  file_name text null,
  description text null,
  constraint files_purchases_suppliers_pkey primary key (id),
  constraint files_purchases_suppliers_storage_path_key unique (storage_path),
  constraint files_purchases_suppliers_purchase_id_fkey foreign key (purchase_supplier_id) references public.purchases_suppliers (id) on update cascade on delete cascade,
  constraint files_purchases_suppliers_description_length_check check (description is null or char_length(description) <= 200)
) TABLESPACE pg_default;

------ INDEXES ------

create index files_purchases_suppliers_purchase_id_idx on public.files_purchases_suppliers (purchase_supplier_id);

------ RLS ------

ALTER TABLE public.files_purchases_suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select files_purchases_suppliers"
ON public.files_purchases_suppliers
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public insert files_purchases_suppliers"
ON public.files_purchases_suppliers
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete files_purchases_suppliers"
ON public.files_purchases_suppliers
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update files_purchases_suppliers"
ON public.files_purchases_suppliers
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);
