------- Files payments suppliers table ------

create table public.files_payments_suppliers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  storage_path text not null,
  payment_supplier_id bigint not null,
  file_name text null,
  description text null,
  constraint files_payments_suppliers_pkey primary key (id),
  constraint files_payments_suppliers_storage_path_key unique (storage_path),
  constraint files_payments_suppliers_payment_id_fkey foreign key (payment_supplier_id) references public.payments_suppliers (id) on update cascade on delete cascade,
  constraint files_payments_suppliers_description_length_check check (description is null or char_length(description) <= 200)
) TABLESPACE pg_default;

------ INDEXES ------

create index files_payments_suppliers_payment_id_idx on public.files_payments_suppliers (payment_supplier_id);

------ RLS ------

ALTER TABLE public.files_payments_suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select files_payments_suppliers"
ON public.files_payments_suppliers
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public insert files_payments_suppliers"
ON public.files_payments_suppliers
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete files_payments_suppliers"
ON public.files_payments_suppliers
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update files_payments_suppliers"
ON public.files_payments_suppliers
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);
