------- Payments suppliers table ------

create table public.payments_suppliers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  amount_ars numeric not null,
  bank_account_id bigint null,
  payment_method_id bigint null,
  purchase_supplier_id bigint not null,
  notes text null,
  constraint payments_suppliers_pkey primary key (id),
  constraint payments_suppliers_bank_account_id_fkey foreign key (bank_account_id) references public.bank_accounts (id) on update cascade on delete set null,
  constraint payments_suppliers_payment_method_id_fkey foreign key (payment_method_id) references public.payment_methods (id) on update cascade on delete set null,
  constraint payments_suppliers_purchase_supplier_id_fkey foreign key (purchase_supplier_id) references public.purchases_suppliers (id) on update cascade on delete restrict,
  constraint payments_suppliers_amount_ars_check check (amount_ars > 0),
  constraint payments_suppliers_notes_length_check check (notes is null or char_length(notes) <= 2000)
) TABLESPACE pg_default;

------ INDEXES ------

create index payments_suppliers_purchase_supplier_id_idx on public.payments_suppliers (purchase_supplier_id);
create index payments_suppliers_bank_account_id_idx on public.payments_suppliers (bank_account_id);
create index payments_suppliers_payment_method_id_idx on public.payments_suppliers (payment_method_id);

------ RLS ------

ALTER TABLE public.payments_suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select payments_suppliers"
ON public.payments_suppliers
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public insert payments_suppliers"
ON public.payments_suppliers
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete payments_suppliers"
ON public.payments_suppliers
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update payments_suppliers"
ON public.payments_suppliers
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

------ RPC: delete a payment and its files atomically ------
CREATE OR REPLACE FUNCTION public.delete_payment_supplier(p_id bigint)
RETURNS text[]
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_file_paths text[];
  v_deleted_id bigint;
BEGIN
  WITH deleted AS (
    DELETE FROM public.files_payments_suppliers
    WHERE payment_supplier_id = p_id
    RETURNING storage_path
  )
  SELECT array_agg(storage_path) INTO v_file_paths FROM deleted;

  DELETE FROM public.payments_suppliers
  WHERE id = p_id
  RETURNING id INTO v_deleted_id;

  IF v_deleted_id IS NULL THEN
    RAISE EXCEPTION 'No se pudo eliminar el pago (no existe o no tenés permisos)';
  END IF;

  RETURN COALESCE(v_file_paths, ARRAY[]::text[]);
END;
$$;

REVOKE ALL ON FUNCTION public.delete_payment_supplier(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_payment_supplier(bigint) TO authenticated;
