------- Purchases suppliers table ------

create table public.purchases_suppliers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  amount_ars numeric not null,
  supplier_id bigint not null,
  notes text null,
  constraint purchases_suppliers_pkey primary key (id),
  constraint purchases_suppliers_supplier_id_fkey foreign key (supplier_id) references public.suppliers (id) on update cascade on delete restrict,
  constraint purchases_suppliers_amount_ars_check check (amount_ars > 0),
  constraint purchases_suppliers_notes_length_check check (notes is null or char_length(notes) <= 2000)
) TABLESPACE pg_default;

------ INDEXES ------

create index purchases_suppliers_supplier_id_idx on public.purchases_suppliers (supplier_id);

------ RLS ------

ALTER TABLE public.purchases_suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select purchases_suppliers"
ON public.purchases_suppliers
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public insert purchases_suppliers"
ON public.purchases_suppliers
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete purchases_suppliers"
ON public.purchases_suppliers
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update purchases_suppliers"
ON public.purchases_suppliers
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

--- RPC for deleting a purchase supplier along with its associated payments and files

CREATE OR REPLACE FUNCTION public.delete_purchase_supplier(p_id bigint)
RETURNS text[]
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_payment_file_paths text[];
  v_purchase_file_paths text[];
  v_deleted_id bigint;
BEGIN

  PERFORM 1 FROM public.purchases_suppliers WHERE id = p_id FOR UPDATE;
  PERFORM 1 FROM public.payments_suppliers WHERE purchase_supplier_id = p_id FOR UPDATE;

  WITH deleted AS (
    DELETE FROM public.files_payments_suppliers f
    USING public.payments_suppliers p
    WHERE f.payment_supplier_id = p.id
      AND p.purchase_supplier_id = p_id
    RETURNING f.storage_path
  )
  SELECT array_agg(storage_path) INTO v_payment_file_paths FROM deleted;

  DELETE FROM public.payments_suppliers
  WHERE purchase_supplier_id = p_id;

  WITH deleted AS (
    DELETE FROM public.files_purchases_suppliers
    WHERE purchase_supplier_id = p_id
    RETURNING storage_path
  )
  SELECT array_agg(storage_path) INTO v_purchase_file_paths FROM deleted;

  DELETE FROM public.purchases_suppliers
  WHERE id = p_id
  RETURNING id INTO v_deleted_id;

  IF v_deleted_id IS NULL THEN
    RAISE EXCEPTION 'No se pudo eliminar la compra (no existe o no tenés permisos)';
  END IF;

  RETURN COALESCE(v_purchase_file_paths, ARRAY[]::text[])
    || COALESCE(v_payment_file_paths, ARRAY[]::text[]);
END;
$$;

REVOKE ALL ON FUNCTION public.delete_purchase_supplier(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_purchase_supplier(bigint) TO authenticated;
