------- Purchases suppliers table ------

create table public.purchases_suppliers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  amount_ars numeric not null,
  supplier_id bigint not null,
  notes text null,
  constraint purchases_suppliers_pkey primary key (id),
  constraint purchases_suppliers_supplier_id_fkey foreign key (supplier_id) references public.suppliers (id) on update cascade on delete restrict,
  constraint purchases_suppliers_amount_ars_check check (amount_ars > 0),
  constraint purchases_suppliers_notes_length_check check (notes is null or char_length(notes) <= 2000)
) TABLESPACE pg_default;

------ INDEXES ------

create index purchases_suppliers_supplier_id_idx on public.purchases_suppliers (supplier_id);

------ RLS ------

ALTER TABLE public.purchases_suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select purchases_suppliers"
ON public.purchases_suppliers
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public insert purchases_suppliers"
ON public.purchases_suppliers
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete purchases_suppliers"
ON public.purchases_suppliers
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update purchases_suppliers"
ON public.purchases_suppliers
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

--- RPC for deleting a purchase supplier along with its associated payments and files

CREATE OR REPLACE FUNCTION public.delete_purchase_supplier(p_id bigint)
RETURNS text[]
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_payment_file_paths text[];
  v_purchase_file_paths text[];
  v_deleted_id bigint;
BEGIN

  PERFORM 1 FROM public.purchases_suppliers WHERE id = p_id FOR UPDATE;
  PERFORM 1 FROM public.payments_suppliers WHERE purchase_supplier_id = p_id FOR UPDATE;

  WITH deleted AS (
    DELETE FROM public.files_payments_suppliers f
    USING public.payments_suppliers p
    WHERE f.payment_supplier_id = p.id
      AND p.purchase_supplier_id = p_id
    RETURNING f.storage_path
  )
  SELECT array_agg(storage_path) INTO v_payment_file_paths FROM deleted;

  DELETE FROM public.payments_suppliers
  WHERE purchase_supplier_id = p_id;

  WITH deleted AS (
    DELETE FROM public.files_purchases_suppliers
    WHERE purchase_supplier_id = p_id
    RETURNING storage_path
  )
  SELECT array_agg(storage_path) INTO v_purchase_file_paths FROM deleted;

  DELETE FROM public.purchases_suppliers
  WHERE id = p_id
  RETURNING id INTO v_deleted_id;

  IF v_deleted_id IS NULL THEN
    RAISE EXCEPTION 'No se pudo eliminar la compra (no existe o no tenés permisos)';
  END IF;

  RETURN COALESCE(v_purchase_file_paths, ARRAY[]::text[])
    || COALESCE(v_payment_file_paths, ARRAY[]::text[]);
END;
$$;

REVOKE ALL ON FUNCTION public.delete_purchase_supplier(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_purchase_supplier(bigint) TO authenticated;

BEGIN;

--- RPC: paginated purchase listing by payment status

CREATE OR REPLACE FUNCTION public.list_supplier_purchases(
  p_supplier_id bigint,
  p_status text,
  p_from date DEFAULT NULL,
  p_to date DEFAULT NULL,
  p_limit int DEFAULT 20,
  p_offset int DEFAULT 0
)
RETURNS TABLE (
  id bigint,
  created_at timestamp with time zone,
  amount_ars numeric,
  supplier_id bigint,
  notes text,
  total_paid_ars numeric,
  balance_ars numeric,
  total_count bigint
)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
STABLE
AS $$
DECLARE
  v_limit int := LEAST(GREATEST(COALESCE(p_limit, 20), 1), 100);
  v_offset int := GREATEST(COALESCE(p_offset, 0), 0);
BEGIN
  IF p_status NOT IN ('pending', 'paid') THEN
    RAISE EXCEPTION 'Estado inválido: % (debe ser pending o paid)', p_status;
  END IF;

  RETURN QUERY
  WITH payments_agg AS (
    SELECT
      ps.purchase_supplier_id,
      SUM(ps.amount_ars) AS total_paid_ars
    FROM public.payments_suppliers ps
    WHERE ps.purchase_supplier_id IN (
      -- aliased: unqualified cols would clash with the OUT params id/supplier_id
      SELECT pp.id FROM public.purchases_suppliers pp WHERE pp.supplier_id = p_supplier_id
    )
    GROUP BY ps.purchase_supplier_id
  ),
  filtered AS (
    SELECT
      p.id,
      p.created_at,
      p.amount_ars,
      p.supplier_id,
      p.notes,
      COALESCE(pa.total_paid_ars, 0) AS total_paid_ars,
      p.amount_ars - COALESCE(pa.total_paid_ars, 0) AS balance_ars
    FROM public.purchases_suppliers p
    LEFT JOIN payments_agg pa ON pa.purchase_supplier_id = p.id
    WHERE p.supplier_id = p_supplier_id
      AND (p_from IS NULL OR (p.created_at AT TIME ZONE 'America/Argentina/Buenos_Aires')::date >= p_from)
      AND (p_to IS NULL OR (p.created_at AT TIME ZONE 'America/Argentina/Buenos_Aires')::date <= p_to)
      AND (
        (p_status = 'pending' AND p.amount_ars - COALESCE(pa.total_paid_ars, 0) > 0)
        OR (p_status = 'paid' AND p.amount_ars - COALESCE(pa.total_paid_ars, 0) <= 0)
      )
  )
  SELECT
    f.id,
    f.created_at,
    f.amount_ars,
    f.supplier_id,
    f.notes,
    f.total_paid_ars,
    f.balance_ars,
    COUNT(*) OVER() AS total_count
  FROM filtered f
  ORDER BY f.created_at DESC, f.id DESC
  LIMIT v_limit
  OFFSET v_offset;
END;
$$;

REVOKE ALL ON FUNCTION public.list_supplier_purchases(bigint, text, date, date, int, int) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.list_supplier_purchases(bigint, text, date, date, int, int) TO authenticated;

COMMIT;

BEGIN;

--- RPC: supplier account totals, independent of date filters

CREATE OR REPLACE FUNCTION public.get_supplier_account_totals(p_supplier_id bigint)
RETURNS TABLE (
  total_purchases_ars numeric,
  total_payments_ars numeric,
  balance_ars numeric,
  pending_count bigint,
  paid_count bigint
)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
STABLE
AS $$
BEGIN
  RETURN QUERY
  WITH payments_agg AS (
    SELECT
      ps.purchase_supplier_id,
      SUM(ps.amount_ars) AS total_paid_ars
    FROM public.payments_suppliers ps
    WHERE ps.purchase_supplier_id IN (
      -- aliased for consistency: keeps every column reference unambiguous
      SELECT pp.id FROM public.purchases_suppliers pp WHERE pp.supplier_id = p_supplier_id
    )
    GROUP BY ps.purchase_supplier_id
  ),
  purchases_with_balance AS (
    SELECT
      p.amount_ars,
      p.amount_ars - COALESCE(pa.total_paid_ars, 0) AS balance_ars
    FROM public.purchases_suppliers p
    LEFT JOIN payments_agg pa ON pa.purchase_supplier_id = p.id
    WHERE p.supplier_id = p_supplier_id
  )
  SELECT
    COALESCE(SUM(pwb.amount_ars), 0) AS total_purchases_ars,
    COALESCE(SUM(pwb.amount_ars - pwb.balance_ars), 0) AS total_payments_ars,
    COALESCE(SUM(pwb.balance_ars), 0) AS balance_ars,
    COUNT(*) FILTER (WHERE pwb.balance_ars > 0) AS pending_count,
    COUNT(*) FILTER (WHERE pwb.balance_ars <= 0) AS paid_count
  FROM purchases_with_balance pwb;
END;
$$;

REVOKE ALL ON FUNCTION public.get_supplier_account_totals(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_supplier_account_totals(bigint) TO authenticated;

COMMIT;
