------- Suppliers table ------

create table public.suppliers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  business_name text null,
  tax_id text null,
  whatsapp text null,
  email text null,
  category text null,
  locality text null,
  address text null,
  payment_terms_days integer null,
  notes text null,
  is_active boolean not null default true,
  constraint suppliers_pkey primary key (id),
  constraint suppliers_payment_terms_days_check check (payment_terms_days is null or (payment_terms_days >= 0 and payment_terms_days <= 3650)),
  constraint suppliers_tax_id_format_check check (tax_id is null or tax_id ~ '^[0-9]{11}$'),
  constraint suppliers_name_length_check check (char_length(name) <= 120),
  constraint suppliers_locality_length_check check (locality is null or char_length(locality) <= 120),
  constraint suppliers_address_length_check check (address is null or char_length(address) <= 200),
  constraint suppliers_email_length_check check (email is null or char_length(email) <= 254),
  constraint suppliers_notes_length_check check (notes is null or char_length(notes) <= 2000)
) TABLESPACE pg_default;

------ INDEXES ------

create unique index suppliers_tax_id_unique_idx on public.suppliers (tax_id) where tax_id is not null;
create index suppliers_name_lower_idx on public.suppliers (lower(name));

------ RLS ------

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public select suppliers"
ON public.suppliers
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public insert suppliers"
ON public.suppliers
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public delete suppliers"
ON public.suppliers
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);

CREATE POLICY "Public update suppliers"
ON public.suppliers
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.uid_user = auth.uid()
            AND u.role = 'Admin'
    )
);
